CREATE DATABASE IF NOT EXISTS authuser_db;
USE authuser_db;
CREATE TABLE auth_users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255)
);
